# Generated by Django 3.0.2 on 2020-02-07 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='topic_link1',
            field=models.CharField(default='default', max_length=300),
            preserve_default=False,
        ),
    ]
