# Generated by Django 3.0.2 on 2020-02-17 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_exam_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='exam_status',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
