# Generated by Django 3.0.2 on 2020-02-20 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_exam_exam_pass'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='test_title',
            field=models.CharField(default='default', max_length=300),
            preserve_default=False,
        ),
    ]
