# Generated by Django 3.0.2 on 2020-02-20 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_test_testmanager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmanager',
            name='related_test',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='courses.Test'),
        ),
    ]
