# Generated by Django 3.0.2 on 2020-02-20 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_auto_20200220_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testmanager',
            name='related_test',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.DeleteModel(
            name='TestManager',
        ),
    ]
