# Generated by Django 3.0.2 on 2020-02-23 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_auto_20200220_2056'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('exam_id', models.IntegerField()),
                ('exam_score', models.FloatField()),
                ('exam_attending_count', models.IntegerField()),
                ('exam_pass_status', models.BooleanField()),
            ],
        ),
    ]
