# Generated by Django 3.0.2 on 2020-02-23 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_auto_20200223_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='exam_manager',
        ),
        migrations.RemoveField(
            model_name='score',
            name='user',
        ),
        migrations.DeleteModel(
            name='Examset',
        ),
        migrations.DeleteModel(
            name='Score',
        ),
    ]
