# Generated by Django 3.0.2 on 2020-02-23 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_auto_20200223_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='userscore',
            name='username',
            field=models.CharField(default='default', max_length=300),
            preserve_default=False,
        ),
    ]
