# Generated by Django 3.0.2 on 2020-02-10 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200210_1939'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
