# Generated by Django 3.0.2 on 2020-02-11 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
