# Generated by Django 3.0.2 on 2020-02-11 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_delete_userinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
