# Generated by Django 3.0.2 on 2020-02-12 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
    ]
