# Generated by Django 3.0.2 on 2020-02-24 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_title', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_subject', models.CharField(max_length=300)),
                ('post_content', models.TextField()),
                ('post_published', models.DateTimeField(auto_now_add=True)),
                ('post_author', models.CharField(max_length=300)),
                ('post_category', models.CharField(max_length=300)),
            ],
        ),
    ]
