# Generated by Django 3.0.2 on 2020-02-25 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_tradeidea'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeidea',
            name='admin_approval',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tradeidea',
            name='trade_status_flag',
            field=models.CharField(max_length=300),
        ),
    ]
