# Generated by Django 3.0.2 on 2020-02-28 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200225_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradeidea',
            name='admin_approval',
            field=models.BooleanField(default=False),
        ),
    ]
